CREATE PROCEDURE [dbo].[TESTTABLE_INSERT]
	@ACTION int  = 0 ,
	@ID int OUTPUT,
	@Value int
AS
BEGIN 
	SET NOCOUNT ON;
	
	INSERT INTO [dbo].TestTable	VALUES( @Value)
	SET @ID =  SCOPE_IDENTITY();
	RETURN @ID

END