CREATE TABLE [dbo].[NETWORK_LAYER]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[ACTIVATION_FUNCTION_ID] INT NOT NULL,
	[NETWORK_ID] INT NOT NULL,
	[NUMBER_OF_NODES] INT NOT NULL, 
    [INTERNAL_INDEX] INT NOT NULL,
)
