CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPSERT]
	@VALUE FLOAT,
	@LAYER_ID INT,
	@INTERNAL_INDEX INT,
	@ID INT OUTPUT
AS
BEGIN
IF EXISTS(SELECT * FROM NETWORK_WEIGHT WHERE ID=@ID)
BEGIN
	UPDATE NETWORK_WEIGHT SET 
	VALUE = @VALUE, LAYER_ID = @LAYER_ID, INTERNAL_INDEX = @INTERNAL_INDEX
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
ELSE
BEGIN
	INSERT INTO NETWORK_WEIGHT VALUES(@VALUE, @LAYER_ID, @INTERNAL_INDEX)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
END
