CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_WEIGHT_TYPE READONLY
AS
BEGIN
	DECLARE @VALUES [dbo].[NETWORK_VALUES_TYPE]

--insert unknown into network values
	INSERT INTO NETWORK_VALUES
	SELECT DISTINCT dt.VALUE from @DATA_TABLE dt
	LEFT JOIN NETWORK_VALUES nv
	ON nv.VALUE = dt.VALUE WHERE nv.VALUE IS NULL

--insert known to temp table @VALUES
	INSERT INTO @VALUES (ID, INTERNAL_INDEX, VALUE_ID, LAYER_ID)
	SELECT 0, dt.INTERNAL_INDEX, nv.ID, dt.LAYER_ID from @DATA_TABLE dt
	INNER JOIN NETWORK_VALUES nv
	ON dt.VALUE = nv.VALUE
-- insert into table
	INSERT INTO NETWORK_WEIGHT (INTERNAL_INDEX, LAYER_ID, VALUE_ID)
	SELECT v.INTERNAL_INDEX, v.LAYER_ID, v.VALUE_ID FROM @VALUES v
-- return values
	SELECT dt.ID, dt.INTERNAL_INDEX, dt.LAYER_ID, v.VALUE_ID FROM @DATA_TABLE dt
	LEFT JOIN @VALUES v
	ON v.INTERNAL_INDEX = dt.INTERNAL_INDEX AND v.LAYER_ID = dt.LAYER_ID AND v.ID IS NOT NULL
END
