CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_INSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@LAYER_ID INT,
	@VALUE FLOAT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO NETWORK_WEIGHT VALUES(@INTERNAL_INDEX, @LAYER_ID, @VALUE)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
