CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPDATE]
	@VALUE FLOAT,
	@LAYER_ID INT,
	@INTERNAL_INDEX INT,
	@ID INT OUTPUT
AS
	UPDATE NETWORK_WEIGHT SET 
	VALUE = @VALUE, LAYER_ID = @LAYER_ID, INTERNAL_INDEX = @INTERNAL_INDEX
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
