CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@LAYER_ID INT,
	@VALUE FLOAT
AS
BEGIN
IF EXISTS(SELECT * FROM NETWORK_WEIGHT WHERE ID=@ID)
BEGIN
	UPDATE NETWORK_WEIGHT SET 
	INTERNAL_INDEX = @INTERNAL_INDEX, LAYER_ID = @LAYER_ID, VALUE = @VALUE
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
ELSE
BEGIN
	INSERT INTO NETWORK_WEIGHT VALUES(@INTERNAL_INDEX, @LAYER_ID, @VALUE)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
END
