CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPDATE]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@LAYER_ID INT,
	@VALUE FLOAT
AS
	UPDATE NETWORK_WEIGHT SET 
	INTERNAL_INDEX = @INTERNAL_INDEX, LAYER_ID = @LAYER_ID, VALUE_ID = @VALUE
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
