CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPDATE]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@LAYER_ID INT,
	@VALUE FLOAT
AS
BEGIN
DECLARE @NEW_ID INT;
IF NOT EXISTS(SELECT TOP(1) V.ID 
FROM NETWORK_VALUES V
WHERE V.VALUE = VALUE)
BEGIN
INSERT INTO NETWORK_VALUES (VALUE)
VALUES(@VALUE)
SET @NEW_ID = SCOPE_IDENTITY()
END
ELSE
BEGIN
SET @NEW_ID = (SELECT TOP(1) ID FROM NETWORK_VALUES V WHERE V.VALUE = @VALUE)
END
UPDATE NETWORK_WEIGHT SET
VALUE_ID = @NEW_ID
WHERE ID = @ID
SET @ID = SCOPE_IDENTITY();
RETURN @ID
END
