CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_WEIGHT_TYPE READONLY
AS
BEGIN
	
	INSERT INTO [dbo].NETWORK_WEIGHT 
	SELECT VALUE, LAYER_ID, INTERNAL_INDEX FROM @DATA_TABLE
	

;
END
RETURN 0
