CREATE PROCEDURE [dbo].[NETWORK_WEIGHT_UPDATE_MANY]
	@DATA_TABLE [dbo].NETWORK_WEIGHT_TYPE READONLY
AS
BEGIN

	UPDATE AT
	SET 	INTERNAL_INDEX = dt.INTERNAL_INDEX,	LAYER_ID = dt.LAYER_ID,	VALUE = dt.VALUE
	FROM NETWORK_WEIGHT tbl
	INNER JOIN @DATA_TABLE dt
		ON tbl.ID = dt.ID

;
END
RETURN 0
