CREATE PROCEDURE [dbo].[NETWORK_BIAS_INSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@VALUE FLOAT,
	@LAYER_ID INT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO NETWORK_BIAS VALUES(@INTERNAL_INDEX, @VALUE, @LAYER_ID)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
