CREATE PROCEDURE [dbo].[NETWORK_BIAS_UPDATE_MANY]
	@DATA_TABLE [dbo].NETWORK_BIAS_TYPE READONLY
AS
BEGIN

	UPDATE AT
	SET 	INTERNAL_INDEX = dt.INTERNAL_INDEX,	VALUE = dt.VALUE,	LAYER_ID = dt.LAYER_ID
	FROM NETWORK_BIAS tbl
	INNER JOIN @DATA_TABLE dt
		ON tbl.ID = dt.ID

;
END
RETURN 0
