CREATE PROCEDURE [dbo].[NETWORK_BIAS_INSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@VALUE FLOAT,
	@LAYER_ID INT
AS
BEGIN
DECLARE @VALUE_ID INT, @RETURN_VALUE INT
EXEC @VALUE_ID = [dbo].[NETWORK_VALUE_TRY_INSERT] @VALUE = @VALUE
INSERT INTO NETWORK_BIAS (INTERNAL_INDEX,LAYER_ID,VALUE_ID)
VALUES(@INTERNAL_INDEX,@LAYER_ID,@VALUE_ID)
RETURN @RETURN_VALUE
END
