CREATE PROCEDURE [dbo].[NETWORK_BIAS_UPDATE]
	@ID INT OUTPUT,
	@VALUE FLOAT
AS
	
	IF NOT EXISTS(SELECT TOP 1 1 FROM NETWORK_VALUES V WHERE  V.VALUE = @VALUE)
		BEGIN
			DECLARE @NEW_ID INT;
			INSERT INTO NETWORK_VALUES (VALUE)
			VALUES(@VALUE)
			SET @NEW_ID = SCOPE_IDENTITY()

			UPDATE NETWORK_BIAS SET 
			 VALUE_ID = @NEW_ID
			WHERE ID=@ID
			SET @ID = SCOPE_IDENTITY();
			RETURN @ID
		END
	ELSE 
		BEGIN
			UPDATE NETWORK_BIAS SET 
			VALUE_ID = (SELECT TOP 1 1 FROM NETWORK_VALUES V WHERE  V.VALUE = @VALUE)
			WHERE ID=@ID
			SET @ID = SCOPE_IDENTITY();
			RETURN @ID
		END