CREATE PROCEDURE [dbo].[NETWORK_BIAS_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_BIAS_TYPE READONLY
AS
BEGIN
	DECLARE @RETURN_VALUE [dbo].NETWORK_BIAS_TYPE

	INSERT INTO [dbo].NETWORK_BIAS
	OUTPUT inserted.ID, inserted.INTERNAL_INDEX, inserted.VALUE_ID, inserted.LAYER_ID INTO @RETURN_VALUE
	SELECT INTERNAL_INDEX, VALUE, LAYER_ID FROM @DATA_TABLE

	SELECT * FROM @RETURN_VALUE
;
END
RETURN 0
