CREATE PROCEDURE [dbo].[NETWORK_BIAS_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_BIAS_TYPE READONLY
AS
BEGIN
	
	INSERT INTO [dbo].NETWORK_BIAS 
	SELECT VALUE, LAYER_ID, INTERNAL_INDEX FROM @DATA_TABLE

;
END
RETURN 0
