CREATE PROCEDURE [dbo].[NETWORK_BIAS_UPSERT]
	@VALUE FLOAT,
	@LAYER_ID INT,
	@INTERNAL_INDEX INT,
	@ID INT OUTPUT
AS
BEGIN
IF EXISTS(SELECT * FROM NETWORK_BIAS WHERE ID=@ID)
BEGIN
	UPDATE NETWORK_BIAS SET 
	VALUE = @VALUE, LAYER_ID = @LAYER_ID, INTERNAL_INDEX = @INTERNAL_INDEX
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
ELSE
BEGIN
	INSERT INTO NETWORK_BIAS VALUES(@VALUE, @LAYER_ID, @INTERNAL_INDEX)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
END
