CREATE PROCEDURE [dbo].[NETWORK_BIAS_GET_BY_ID]
	@ID INT
AS
BEGIN
SELECT A.ID,A.INTERNAL_INDEX,A.LAYER_ID,B.VALUE  FROM [dbo].NETWORK_BIAS A
LEFT JOIN NETWORK_VALUES B
ON A.VALUE_ID = B.ID
WHERE A.ID = @ID
END
