CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPDATE]
	@ACTIVATION_FUNCTION_ID INT ,
	@NETWORK_ID INT ,
	@NUMBER_OF_NODES INT ,
	@INTERNAL_INDEX INT ,
	@ID INT OUTPUT
AS
	UPDATE NETWORK_LAYER SET 
	ACTIVATION_FUNCTION_ID = @ACTIVATION_FUNCTION_ID, NETWORK_ID = @NETWORK_ID, NUMBER_OF_NODES = @NUMBER_OF_NODES, INTERNAL_INDEX = @INTERNAL_INDEX
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
