CREATE PROCEDURE [dbo].[NETWORK_LAYER_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN
	MERGE [dbo].NETWORK_LAYER as dbTable
	USING @DATA_TABLE as tbl
	ON (dbTable.Id = tbl.Id)


	WHEN NOT MATCHED THEN
		INSERT ([ACTIVATION_FUNCTION_ID], [NETWORK_ID], [NUMBER_OF_NODES], [INTERNAL_INDEX])
		VALUES(tbl.ACTIVATION_FUNCTION_ID, tbl.NETWORK_ID, tbl.NUMBER_OF_NODES, tbl.INTERNAL_INDEX);

END
RETURN 0
