CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN
	MERGE [dbo].NETWORK_LAYER as dbTable
	USING @DATA_TABLE as tbl
	ON (dbTable.Id = tbl.Id)

	WHEN MATCHED THEN
		UPDATE SET  
			dbTable.ACTIVATION_FUNCTION_ID = tbl.ACTIVATION_FUNCTION_ID, 
			dbTable.NETWORK_ID = tbl.NETWORK_ID, 
			dbTable.NUMBER_OF_NODES = tbl.NUMBER_OF_NODES, 
			dbTable.INTERNAL_INDEX = tbl.INTERNAL_INDEX


	WHEN NOT MATCHED THEN
		INSERT ([ACTIVATION_FUNCTION_ID], [NETWORK_ID], [NUMBER_OF_NODES], [INTERNAL_INDEX])
		VALUES(tbl.ACTIVATION_FUNCTION_ID, tbl.NETWORK_ID, tbl.NUMBER_OF_NODES, tbl.INTERNAL_INDEX);

;
END
RETURN 0
