CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@ACTIVATION_FUNCTION_ID INT,
	@NETWORK_ID INT,
	@NUMBER_OF_NODES INT
AS
BEGIN
IF EXISTS(SELECT * FROM NETWORK_LAYER WHERE ID=@ID)
BEGIN
	UPDATE NETWORK_LAYER SET 
	INTERNAL_INDEX = @INTERNAL_INDEX, ACTIVATION_FUNCTION_ID = @ACTIVATION_FUNCTION_ID, NETWORK_ID = @NETWORK_ID, NUMBER_OF_NODES = @NUMBER_OF_NODES
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
ELSE
BEGIN
	INSERT INTO NETWORK_LAYER VALUES(@INTERNAL_INDEX, @ACTIVATION_FUNCTION_ID, @NETWORK_ID, @NUMBER_OF_NODES)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
END
