CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPDATE]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@ACTIVATION_FUNCTION_ID INT,
	@NETWORK_ID INT,
	@NUMBER_OF_NODES INT
AS
	UPDATE NETWORK_LAYER SET 
	INTERNAL_INDEX = @INTERNAL_INDEX, ACTIVATION_FUNCTION_ID = @ACTIVATION_FUNCTION_ID, NETWORK_ID = @NETWORK_ID, NUMBER_OF_NODES = @NUMBER_OF_NODES
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
