CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPDATE_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN

	UPDATE AT
	SET 	INTERNAL_INDEX = dt.INTERNAL_INDEX,	ACTIVATION_FUNCTION_ID = dt.ACTIVATION_FUNCTION_ID,	NETWORK_ID = dt.NETWORK_ID,	NUMBER_OF_NODES = dt.NUMBER_OF_NODES
	FROM NETWORK_LAYER tbl
	INNER JOIN @DATA_TABLE dt
		ON tbl.ID = dt.ID

;
RETURN 0
END
