CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPDATE_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN
	MERGE [dbo].NETWORK_LAYER as dbTable
	USING @DATA_TABLE as tbl
	ON (dbTable.Id = tbl.Id)

	WHEN MATCHED THEN
		UPDATE SET  
			dbTable.ACTIVATION_FUNCTION_ID = tbl.ACTIVATION_FUNCTION_ID,
			dbTable.NETWORK_ID = tbl.NETWORK_ID,
			dbTable.NUMBER_OF_NODES = tbl.NUMBER_OF_NODES,
			dbTable.INTERNAL_INDEX = tbl.INTERNAL_INDEX


;
END
RETURN 0
