CREATE PROCEDURE [dbo].[NETWORK_LAYER_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN
	
	INSERT INTO [dbo].NETWORK_LAYER 
	SELECT ACTIVATION_FUNCTION_ID, NETWORK_ID, NUMBER_OF_NODES, INTERNAL_INDEX FROM @DATA_TABLE
;
END
RETURN 0
