CREATE PROCEDURE [dbo].[NETWORK_LAYER_INSERT_MANY]
	@DATA_TABLE [dbo].NETWORK_LAYER_TYPE READONLY
AS
BEGIN
	DECLARE @RETURN_VALUE [dbo].NETWORK_LAYER_TYPE

	INSERT INTO [dbo].NETWORK_LAYER
	OUTPUT inserted.ID, inserted.INTERNAL_INDEX, inserted.ACTIVATION_FUNCTION_ID, inserted.NETWORK_ID, inserted.NUMBER_OF_NODES INTO @RETURN_VALUE
	SELECT INTERNAL_INDEX, ACTIVATION_FUNCTION_ID, NETWORK_ID, NUMBER_OF_NODES FROM @DATA_TABLE

	SELECT * FROM @RETURN_VALUE
;
END
RETURN 0
