CREATE PROCEDURE [dbo].[NETWORK_LAYER_INSERT]
	@ACTIVATION_FUNCTION_ID INT ,
	@NETWORK_ID INT ,
	@NUMBER_OF_NODES INT ,
	@INTERNAL_INDEX INT ,
	@ID INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO NETWORK_LAYER VALUES(@ACTIVATION_FUNCTION_ID, @NETWORK_ID, @NUMBER_OF_NODES, @INTERNAL_INDEX)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
