CREATE PROCEDURE [dbo].[NETWORK_LAYER_INSERT]
	@ID INT OUTPUT,
	@INTERNAL_INDEX INT,
	@ACTIVATION_FUNCTION_ID INT,
	@NETWORK_ID INT,
	@NUMBER_OF_NODES INT
AS
BEGIN
	SET NOCOUNT ON

	INSERT INTO NETWORK_LAYER VALUES(@INTERNAL_INDEX, @ACTIVATION_FUNCTION_ID, @NETWORK_ID, @NUMBER_OF_NODES)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
