CREATE PROCEDURE [dbo].[NETWORK_LAYER_UPSERT]
	@ACTIVATION_FUNCTION_ID INT ,
	@NETWORK_ID INT ,
	@NUMBER_OF_NODES INT ,
	@INTERNAL_INDEX INT ,
	@ID INT OUTPUT
AS
BEGIN
IF EXISTS(SELECT * FROM NETWORK_LAYER WHERE ID=@ID)
BEGIN
	UPDATE NETWORK_LAYER SET 
	ACTIVATION_FUNCTION_ID = @ACTIVATION_FUNCTION_ID, NETWORK_ID = @NETWORK_ID, NUMBER_OF_NODES = @NUMBER_OF_NODES, INTERNAL_INDEX = @INTERNAL_INDEX
	WHERE ID=@ID
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
ELSE
BEGIN
	INSERT INTO NETWORK_LAYER VALUES(@ACTIVATION_FUNCTION_ID, @NETWORK_ID, @NUMBER_OF_NODES, @INTERNAL_INDEX)
	SET @ID = SCOPE_IDENTITY();
	RETURN @ID
END
END
